// 本文件管理政策候选的人工审核与正式资料衔接；候选原文只停留在候选表，绝不直接进入 RAG。
import { eq, and } from "drizzle-orm";
import { getDb } from "../db";
import { approvals, documentVersions, documents, policyCandidates, policySources } from "../db/schema";
import type { AccessUser } from "./access";
import { indexDocumentVersion } from "./ingestion";

async function hash(value: string) { const data = new TextEncoder().encode(value); return [...new Uint8Array(await crypto.subtle.digest("SHA-256", data))].map((x) => x.toString(16).padStart(2, "0")).join(""); }
export async function createPolicyCandidate(user: AccessUser, input: { policySourceId: string; title: string; rawContent: string; documentNumber?: string; issuingBody?: string; publishDate?: string; effectiveDate?: string; sourceReference?: string }) {
  if (user.role !== "system_admin") return "forbidden" as const; const db = getDb(); const contentHash = await hash(input.rawContent.trim());
  const [source] = await db.select().from(policySources).where(and(eq(policySources.id, input.policySourceId), eq(policySources.status, "enabled"))).limit(1); if (!source) return null;
  const [existing] = await db.select().from(policyCandidates).where(and(eq(policyCandidates.policySourceId, input.policySourceId), eq(policyCandidates.title, input.title.trim()), eq(policyCandidates.contentHash, contentHash))).limit(1); if (existing) return { candidate: existing, created: false };
  const now = new Date().toISOString(); const id = crypto.randomUUID(); await db.insert(policyCandidates).values({ id, policySourceId: input.policySourceId, title: input.title.trim(), documentNumber: input.documentNumber?.trim() || null, issuingBody: input.issuingBody?.trim() || null, publishDate: input.publishDate?.trim() || null, effectiveDate: input.effectiveDate?.trim() || null, sourceReference: input.sourceReference?.trim() || null, rawContent: input.rawContent.trim(), contentHash, status: "PENDING_REVIEW", createdAt: now, updatedAt: now });
  const [candidate] = await db.select().from(policyCandidates).where(eq(policyCandidates.id, id)); return { candidate, created: true };
}
export async function reviewPolicyCandidate(user: AccessUser, id: string, decision: "approve" | "reject", comment: string) {
  if (user.role !== "system_admin") return "forbidden" as const; const db = getDb(); const [candidate] = await db.select().from(policyCandidates).where(eq(policyCandidates.id, id)).limit(1); if (!candidate) return null; if (candidate.status !== "PENDING_REVIEW") return "invalid" as const;
  const now = new Date().toISOString(); if (decision === "reject") { await db.update(policyCandidates).set({ status: "REJECTED", reviewedBy: user.name, reviewedAt: now, reviewComment: comment, updatedAt: now }).where(eq(policyCandidates.id, id)); return { status: "REJECTED" }; }
  const documentId = crypto.randomUUID(), versionId = crypto.randomUUID(); await db.insert(documents).values({ id: documentId, title: candidate.title, documentType: "政策文件", sourceType: "policy_candidate", sourceRef: candidate.id, ownerDepartment: user.departmentName, securityLevel: "内部", permissionScope: "集团本部", lifecycleStatus: "effective", trialDataClass: "T2-内部脱敏测试", isTrialData: true, resourceStatus: "pending_review", resourceCategory: "制度规范", sourceOrganization: candidate.issuingBody, documentDate: candidate.publishDate, applicableScope: "待审核", reliabilityScore: 0, knowledgeStatus: "pending", currentVersion: 1, createdBy: user.name, createdByUserId: user.id, createdAt: now, updatedAt: now }); await db.insert(documentVersions).values({ id: versionId, documentId, versionNo: 1, content: candidate.rawContent, changeSummary: "政策候选人工审核通过后提交正式资料审核", versionStatus: "pending", createdBy: user.name, createdAt: now }); await indexDocumentVersion(documentId, versionId, candidate.rawContent, { title: candidate.title }); await db.insert(approvals).values({ id: crypto.randomUUID(), documentId, versionId, status: "pending", submittedBy: user.name, submittedAt: now }); await db.update(policyCandidates).set({ status: "APPROVED", reviewedBy: user.name, reviewedAt: now, reviewComment: comment, knowledgeDocumentId: documentId, knowledgeVersionId: versionId, updatedAt: now }).where(eq(policyCandidates.id, id)); return { status: "APPROVED", documentId, versionId };
}
